### ISSUE TITLE
Deploy crashed on start

### ISSUE THREAD

**Issue by SiAdcock** [WDOTS/deploy#3]
@Jameskmonger 

`deploy` was at status `errored` on the server so I stopped it and restarted. However it immediately errors on restart. I've got a few questions:
1. The `deploy` git repo on the server has unstaged changes, I think `pull.sh` has been chmod-ed. Can we get this change committed and pushed, if we need it? I suspect we do.
2. There is no automated deploy for the `deploy` job. Not sure if there's any way around this!
3. Is there any logging for pm2 or the deploy job? It would be really useful if we can get something set up.

**Comment by Jameskmonger** [comment]
@SiAdcock 

Yeah the changes to `pull.sh` are just the results of `sudo chmod u+x pull.sh`, which could be committed to the repo to allow pulling deploy easier.

pm2 logs can be seen in `~/.pm2/`, and I'll take a look into those tomorrow morning. Thanks!

**Comment by SiAdcock** [comment]
Ah nice one, thanks man.

The issue was chimneypot was not installed locally in the deploy directory on the server. I ran `npm install` and it's now up and running.

I've also committed the permissions change to the repo.
